#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BottleSlot

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function BottleSlot.BottleSlot_C.ExecuteUbergraph_BottleSlot
// 0x02D0 (0x02D0 - 0x0000)
struct BottleSlot_C_ExecuteUbergraph_BottleSlot final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0xC];                                        // 0x0004(0x000C)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             CallFunc_K2_GetComponentToWorld_ReturnValue;       // 0x0010(0x0060)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue; // 0x0070(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class AExplosion_C*                           CallFunc_FinishSpawningActor_ReturnValue;          // 0x0078(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Conv_IntToVector_ReturnValue;             // 0x0080(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Conv_IntToVector_ReturnValue_1;           // 0x0098(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_CustomEvent_Pressure;                       // 0x00B0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Clamp_ReturnValue;                        // 0x00B4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Multiply_IntInt_ReturnValue;              // 0x00B8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Subtract_IntInt_ReturnValue;              // 0x00BC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_CustomEvent_True;                           // 0x00C0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchInteger_CmpSuccess;                   // 0x00C4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_C5[0x3];                                       // 0x00C5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         K2Node_CustomEvent_Value;                          // 0x00C8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Clamp_ReturnValue_1;                      // 0x00CC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_IntInt_ReturnValue;               // 0x00D0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_D1[0x3];                                       // 0x00D1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Multiply_IntInt_ReturnValue_1;            // 0x00D4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x00D8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_IntInt_ReturnValue_1;             // 0x00DC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_IntInt_ReturnValue;            // 0x00DD(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_DE[0x2];                                       // 0x00DE(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             CallFunc_K2_GetComponentToWorld_ReturnValue_1;     // 0x00E0(0x0060)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakTransform_Location;                  // 0x0140(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_BreakTransform_Rotation;                  // 0x0158(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_BreakTransform_Scale;                     // 0x0170(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_GetForwardVector_ReturnValue;             // 0x0188(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Multiply_VectorVector_ReturnValue;        // 0x01A0(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Multiply_VectorVector_ReturnValue_1;      // 0x01B8(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Add_VectorVector_ReturnValue;             // 0x01D0(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1E8[0x8];                                      // 0x01E8(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             CallFunc_MakeTransform_ReturnValue;                // 0x01F0(0x0060)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue_1; // 0x0250(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_SelectInt_ReturnValue;                    // 0x0258(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_SelectInt_ReturnValue_1;                  // 0x025C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_NotEqual_IntInt_ReturnValue;              // 0x0260(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_261[0x7];                                      // 0x0261(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AWorldItem_C*                           CallFunc_FinishSpawningActor_ReturnValue_1;        // 0x0268(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0270(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FTimerHandle                           CallFunc_K2_SetTimerDelegate_ReturnValue;          // 0x0280(0x0008)(NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_HasAuthority_ReturnValue;                 // 0x0288(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_289[0x7];                                      // 0x0289(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue;          // 0x0290(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UAudioComponent*                        CallFunc_SpawnSoundAtLocation_ReturnValue;         // 0x02A8(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UAudioComponent*                        CallFunc_SpawnSoundAttached_ReturnValue;           // 0x02B0(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_IntInt_ReturnValue_2;             // 0x02B8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2B9[0x3];                                      // 0x02B9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Subtract_IntInt_ReturnValue_1;            // 0x02BC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_IntInt_ReturnValue_3;             // 0x02C0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_IntInt_ReturnValue_4;             // 0x02C1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_IntInt_ReturnValue_5;             // 0x02C2(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BottleSlot_C_ExecuteUbergraph_BottleSlot) == 0x000010, "Wrong alignment on BottleSlot_C_ExecuteUbergraph_BottleSlot");
static_assert(sizeof(BottleSlot_C_ExecuteUbergraph_BottleSlot) == 0x0002D0, "Wrong size on BottleSlot_C_ExecuteUbergraph_BottleSlot");
static_assert(offsetof(BottleSlot_C_ExecuteUbergraph_BottleSlot, EntryPoint) == 0x000000, "Member 'BottleSlot_C_ExecuteUbergraph_BottleSlot::EntryPoint' has a wrong offset!");
static_assert(offsetof(BottleSlot_C_ExecuteUbergraph_BottleSlot, CallFunc_K2_GetComponentToWorld_ReturnValue) == 0x000010, "Member 'BottleSlot_C_ExecuteUbergraph_BottleSlot::CallFunc_K2_GetComponentToWorld_ReturnValue' has a wrong offset!");
static_assert(offsetof(BottleSlot_C_ExecuteUbergraph_BottleSlot, CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue) == 0x000070, "Member 'BottleSlot_C_ExecuteUbergraph_BottleSlot::CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(BottleSlot_C_ExecuteUbergraph_BottleSlot, CallFunc_FinishSpawningActor_ReturnValue) == 0x000078, "Member 'BottleSlot_C_ExecuteUbergraph_BottleSlot::CallFunc_FinishSpawningActor_ReturnValue' has a wrong offset!");
static_assert(offsetof(BottleSlot_C_ExecuteUbergraph_BottleSlot, CallFunc_Conv_IntToVector_ReturnValue) == 0x000080, "Member 'BottleSlot_C_ExecuteUbergraph_BottleSlot::CallFunc_Conv_IntToVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(BottleSlot_C_ExecuteUbergraph_BottleSlot, CallFunc_Conv_IntToVector_ReturnValue_1) == 0x000098, "Member 'BottleSlot_C_ExecuteUbergraph_BottleSlot::CallFunc_Conv_IntToVector_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BottleSlot_C_ExecuteUbergraph_BottleSlot, K2Node_CustomEvent_Pressure) == 0x0000B0, "Member 'BottleSlot_C_ExecuteUbergraph_BottleSlot::K2Node_CustomEvent_Pressure' has a wrong offset!");
static_assert(offsetof(BottleSlot_C_ExecuteUbergraph_BottleSlot, CallFunc_Clamp_ReturnValue) == 0x0000B4, "Member 'BottleSlot_C_ExecuteUbergraph_BottleSlot::CallFunc_Clamp_ReturnValue' has a wrong offset!");
static_assert(offsetof(BottleSlot_C_ExecuteUbergraph_BottleSlot, CallFunc_Multiply_IntInt_ReturnValue) == 0x0000B8, "Member 'BottleSlot_C_ExecuteUbergraph_BottleSlot::CallFunc_Multiply_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BottleSlot_C_ExecuteUbergraph_BottleSlot, CallFunc_Subtract_IntInt_ReturnValue) == 0x0000BC, "Member 'BottleSlot_C_ExecuteUbergraph_BottleSlot::CallFunc_Subtract_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BottleSlot_C_ExecuteUbergraph_BottleSlot, K2Node_CustomEvent_True) == 0x0000C0, "Member 'BottleSlot_C_ExecuteUbergraph_BottleSlot::K2Node_CustomEvent_True' has a wrong offset!");
static_assert(offsetof(BottleSlot_C_ExecuteUbergraph_BottleSlot, K2Node_SwitchInteger_CmpSuccess) == 0x0000C4, "Member 'BottleSlot_C_ExecuteUbergraph_BottleSlot::K2Node_SwitchInteger_CmpSuccess' has a wrong offset!");
static_assert(offsetof(BottleSlot_C_ExecuteUbergraph_BottleSlot, K2Node_CustomEvent_Value) == 0x0000C8, "Member 'BottleSlot_C_ExecuteUbergraph_BottleSlot::K2Node_CustomEvent_Value' has a wrong offset!");
static_assert(offsetof(BottleSlot_C_ExecuteUbergraph_BottleSlot, CallFunc_Clamp_ReturnValue_1) == 0x0000CC, "Member 'BottleSlot_C_ExecuteUbergraph_BottleSlot::CallFunc_Clamp_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BottleSlot_C_ExecuteUbergraph_BottleSlot, CallFunc_Greater_IntInt_ReturnValue) == 0x0000D0, "Member 'BottleSlot_C_ExecuteUbergraph_BottleSlot::CallFunc_Greater_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BottleSlot_C_ExecuteUbergraph_BottleSlot, CallFunc_Multiply_IntInt_ReturnValue_1) == 0x0000D4, "Member 'BottleSlot_C_ExecuteUbergraph_BottleSlot::CallFunc_Multiply_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BottleSlot_C_ExecuteUbergraph_BottleSlot, CallFunc_Add_IntInt_ReturnValue) == 0x0000D8, "Member 'BottleSlot_C_ExecuteUbergraph_BottleSlot::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BottleSlot_C_ExecuteUbergraph_BottleSlot, CallFunc_Greater_IntInt_ReturnValue_1) == 0x0000DC, "Member 'BottleSlot_C_ExecuteUbergraph_BottleSlot::CallFunc_Greater_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BottleSlot_C_ExecuteUbergraph_BottleSlot, CallFunc_EqualEqual_IntInt_ReturnValue) == 0x0000DD, "Member 'BottleSlot_C_ExecuteUbergraph_BottleSlot::CallFunc_EqualEqual_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BottleSlot_C_ExecuteUbergraph_BottleSlot, CallFunc_K2_GetComponentToWorld_ReturnValue_1) == 0x0000E0, "Member 'BottleSlot_C_ExecuteUbergraph_BottleSlot::CallFunc_K2_GetComponentToWorld_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BottleSlot_C_ExecuteUbergraph_BottleSlot, CallFunc_BreakTransform_Location) == 0x000140, "Member 'BottleSlot_C_ExecuteUbergraph_BottleSlot::CallFunc_BreakTransform_Location' has a wrong offset!");
static_assert(offsetof(BottleSlot_C_ExecuteUbergraph_BottleSlot, CallFunc_BreakTransform_Rotation) == 0x000158, "Member 'BottleSlot_C_ExecuteUbergraph_BottleSlot::CallFunc_BreakTransform_Rotation' has a wrong offset!");
static_assert(offsetof(BottleSlot_C_ExecuteUbergraph_BottleSlot, CallFunc_BreakTransform_Scale) == 0x000170, "Member 'BottleSlot_C_ExecuteUbergraph_BottleSlot::CallFunc_BreakTransform_Scale' has a wrong offset!");
static_assert(offsetof(BottleSlot_C_ExecuteUbergraph_BottleSlot, CallFunc_GetForwardVector_ReturnValue) == 0x000188, "Member 'BottleSlot_C_ExecuteUbergraph_BottleSlot::CallFunc_GetForwardVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(BottleSlot_C_ExecuteUbergraph_BottleSlot, CallFunc_Multiply_VectorVector_ReturnValue) == 0x0001A0, "Member 'BottleSlot_C_ExecuteUbergraph_BottleSlot::CallFunc_Multiply_VectorVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(BottleSlot_C_ExecuteUbergraph_BottleSlot, CallFunc_Multiply_VectorVector_ReturnValue_1) == 0x0001B8, "Member 'BottleSlot_C_ExecuteUbergraph_BottleSlot::CallFunc_Multiply_VectorVector_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BottleSlot_C_ExecuteUbergraph_BottleSlot, CallFunc_Add_VectorVector_ReturnValue) == 0x0001D0, "Member 'BottleSlot_C_ExecuteUbergraph_BottleSlot::CallFunc_Add_VectorVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(BottleSlot_C_ExecuteUbergraph_BottleSlot, CallFunc_MakeTransform_ReturnValue) == 0x0001F0, "Member 'BottleSlot_C_ExecuteUbergraph_BottleSlot::CallFunc_MakeTransform_ReturnValue' has a wrong offset!");
static_assert(offsetof(BottleSlot_C_ExecuteUbergraph_BottleSlot, CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue_1) == 0x000250, "Member 'BottleSlot_C_ExecuteUbergraph_BottleSlot::CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BottleSlot_C_ExecuteUbergraph_BottleSlot, CallFunc_SelectInt_ReturnValue) == 0x000258, "Member 'BottleSlot_C_ExecuteUbergraph_BottleSlot::CallFunc_SelectInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BottleSlot_C_ExecuteUbergraph_BottleSlot, CallFunc_SelectInt_ReturnValue_1) == 0x00025C, "Member 'BottleSlot_C_ExecuteUbergraph_BottleSlot::CallFunc_SelectInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BottleSlot_C_ExecuteUbergraph_BottleSlot, CallFunc_NotEqual_IntInt_ReturnValue) == 0x000260, "Member 'BottleSlot_C_ExecuteUbergraph_BottleSlot::CallFunc_NotEqual_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BottleSlot_C_ExecuteUbergraph_BottleSlot, CallFunc_FinishSpawningActor_ReturnValue_1) == 0x000268, "Member 'BottleSlot_C_ExecuteUbergraph_BottleSlot::CallFunc_FinishSpawningActor_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BottleSlot_C_ExecuteUbergraph_BottleSlot, K2Node_CreateDelegate_OutputDelegate) == 0x000270, "Member 'BottleSlot_C_ExecuteUbergraph_BottleSlot::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(BottleSlot_C_ExecuteUbergraph_BottleSlot, CallFunc_K2_SetTimerDelegate_ReturnValue) == 0x000280, "Member 'BottleSlot_C_ExecuteUbergraph_BottleSlot::CallFunc_K2_SetTimerDelegate_ReturnValue' has a wrong offset!");
static_assert(offsetof(BottleSlot_C_ExecuteUbergraph_BottleSlot, CallFunc_HasAuthority_ReturnValue) == 0x000288, "Member 'BottleSlot_C_ExecuteUbergraph_BottleSlot::CallFunc_HasAuthority_ReturnValue' has a wrong offset!");
static_assert(offsetof(BottleSlot_C_ExecuteUbergraph_BottleSlot, CallFunc_K2_GetActorLocation_ReturnValue) == 0x000290, "Member 'BottleSlot_C_ExecuteUbergraph_BottleSlot::CallFunc_K2_GetActorLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BottleSlot_C_ExecuteUbergraph_BottleSlot, CallFunc_SpawnSoundAtLocation_ReturnValue) == 0x0002A8, "Member 'BottleSlot_C_ExecuteUbergraph_BottleSlot::CallFunc_SpawnSoundAtLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BottleSlot_C_ExecuteUbergraph_BottleSlot, CallFunc_SpawnSoundAttached_ReturnValue) == 0x0002B0, "Member 'BottleSlot_C_ExecuteUbergraph_BottleSlot::CallFunc_SpawnSoundAttached_ReturnValue' has a wrong offset!");
static_assert(offsetof(BottleSlot_C_ExecuteUbergraph_BottleSlot, CallFunc_Greater_IntInt_ReturnValue_2) == 0x0002B8, "Member 'BottleSlot_C_ExecuteUbergraph_BottleSlot::CallFunc_Greater_IntInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BottleSlot_C_ExecuteUbergraph_BottleSlot, CallFunc_Subtract_IntInt_ReturnValue_1) == 0x0002BC, "Member 'BottleSlot_C_ExecuteUbergraph_BottleSlot::CallFunc_Subtract_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BottleSlot_C_ExecuteUbergraph_BottleSlot, CallFunc_Greater_IntInt_ReturnValue_3) == 0x0002C0, "Member 'BottleSlot_C_ExecuteUbergraph_BottleSlot::CallFunc_Greater_IntInt_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BottleSlot_C_ExecuteUbergraph_BottleSlot, CallFunc_Greater_IntInt_ReturnValue_4) == 0x0002C1, "Member 'BottleSlot_C_ExecuteUbergraph_BottleSlot::CallFunc_Greater_IntInt_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(BottleSlot_C_ExecuteUbergraph_BottleSlot, CallFunc_Greater_IntInt_ReturnValue_5) == 0x0002C2, "Member 'BottleSlot_C_ExecuteUbergraph_BottleSlot::CallFunc_Greater_IntInt_ReturnValue_5' has a wrong offset!");

// Function BottleSlot.BottleSlot_C.Get Map Position
// 0x0078 (0x0078 - 0x0000)
struct BottleSlot_C_Get_Map_Position final
{
public:
	struct FVector                                Location;                                          // 0x0000(0x0018)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetComponentLocation_ReturnValue;      // 0x0018(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector_X;                            // 0x0030(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector_Y;                            // 0x0038(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector_Z;                            // 0x0040(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector_X_1;                          // 0x0048(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector_Y_1;                          // 0x0050(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector_Z_1;                          // 0x0058(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_MakeVector_ReturnValue;                   // 0x0060(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BottleSlot_C_Get_Map_Position) == 0x000008, "Wrong alignment on BottleSlot_C_Get_Map_Position");
static_assert(sizeof(BottleSlot_C_Get_Map_Position) == 0x000078, "Wrong size on BottleSlot_C_Get_Map_Position");
static_assert(offsetof(BottleSlot_C_Get_Map_Position, Location) == 0x000000, "Member 'BottleSlot_C_Get_Map_Position::Location' has a wrong offset!");
static_assert(offsetof(BottleSlot_C_Get_Map_Position, CallFunc_K2_GetComponentLocation_ReturnValue) == 0x000018, "Member 'BottleSlot_C_Get_Map_Position::CallFunc_K2_GetComponentLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BottleSlot_C_Get_Map_Position, CallFunc_BreakVector_X) == 0x000030, "Member 'BottleSlot_C_Get_Map_Position::CallFunc_BreakVector_X' has a wrong offset!");
static_assert(offsetof(BottleSlot_C_Get_Map_Position, CallFunc_BreakVector_Y) == 0x000038, "Member 'BottleSlot_C_Get_Map_Position::CallFunc_BreakVector_Y' has a wrong offset!");
static_assert(offsetof(BottleSlot_C_Get_Map_Position, CallFunc_BreakVector_Z) == 0x000040, "Member 'BottleSlot_C_Get_Map_Position::CallFunc_BreakVector_Z' has a wrong offset!");
static_assert(offsetof(BottleSlot_C_Get_Map_Position, CallFunc_BreakVector_X_1) == 0x000048, "Member 'BottleSlot_C_Get_Map_Position::CallFunc_BreakVector_X_1' has a wrong offset!");
static_assert(offsetof(BottleSlot_C_Get_Map_Position, CallFunc_BreakVector_Y_1) == 0x000050, "Member 'BottleSlot_C_Get_Map_Position::CallFunc_BreakVector_Y_1' has a wrong offset!");
static_assert(offsetof(BottleSlot_C_Get_Map_Position, CallFunc_BreakVector_Z_1) == 0x000058, "Member 'BottleSlot_C_Get_Map_Position::CallFunc_BreakVector_Z_1' has a wrong offset!");
static_assert(offsetof(BottleSlot_C_Get_Map_Position, CallFunc_MakeVector_ReturnValue) == 0x000060, "Member 'BottleSlot_C_Get_Map_Position::CallFunc_MakeVector_ReturnValue' has a wrong offset!");

// Function BottleSlot.BottleSlot_C.OnRep_Lock
// 0x0018 (0x0018 - 0x0000)
struct BottleSlot_C_OnRep_Lock final
{
public:
	struct FVector                                CallFunc_SelectVector_ReturnValue;                 // 0x0000(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BottleSlot_C_OnRep_Lock) == 0x000008, "Wrong alignment on BottleSlot_C_OnRep_Lock");
static_assert(sizeof(BottleSlot_C_OnRep_Lock) == 0x000018, "Wrong size on BottleSlot_C_OnRep_Lock");
static_assert(offsetof(BottleSlot_C_OnRep_Lock, CallFunc_SelectVector_ReturnValue) == 0x000000, "Member 'BottleSlot_C_OnRep_Lock::CallFunc_SelectVector_ReturnValue' has a wrong offset!");

// Function BottleSlot.BottleSlot_C.Set Pressure
// 0x0004 (0x0004 - 0x0000)
struct BottleSlot_C_Set_Pressure final
{
public:
	int32                                         Pressure_0;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BottleSlot_C_Set_Pressure) == 0x000004, "Wrong alignment on BottleSlot_C_Set_Pressure");
static_assert(sizeof(BottleSlot_C_Set_Pressure) == 0x000004, "Wrong size on BottleSlot_C_Set_Pressure");
static_assert(offsetof(BottleSlot_C_Set_Pressure, Pressure_0) == 0x000000, "Member 'BottleSlot_C_Set_Pressure::Pressure_0' has a wrong offset!");

// Function BottleSlot.BottleSlot_C.Set State
// 0x0004 (0x0004 - 0x0000)
struct BottleSlot_C_Set_State final
{
public:
	int32                                         TRUE_0;                                            // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BottleSlot_C_Set_State) == 0x000004, "Wrong alignment on BottleSlot_C_Set_State");
static_assert(sizeof(BottleSlot_C_Set_State) == 0x000004, "Wrong size on BottleSlot_C_Set_State");
static_assert(offsetof(BottleSlot_C_Set_State, TRUE_0) == 0x000000, "Member 'BottleSlot_C_Set_State::TRUE_0' has a wrong offset!");

// Function BottleSlot.BottleSlot_C.Try Set State
// 0x0004 (0x0004 - 0x0000)
struct BottleSlot_C_Try_Set_State final
{
public:
	int32                                         Value;                                             // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BottleSlot_C_Try_Set_State) == 0x000004, "Wrong alignment on BottleSlot_C_Try_Set_State");
static_assert(sizeof(BottleSlot_C_Try_Set_State) == 0x000004, "Wrong size on BottleSlot_C_Try_Set_State");
static_assert(offsetof(BottleSlot_C_Try_Set_State, Value) == 0x000000, "Member 'BottleSlot_C_Try_Set_State::Value' has a wrong offset!");

// Function BottleSlot.BottleSlot_C.UserConstructionScript
// 0x0250 (0x0250 - 0x0000)
struct BottleSlot_C_UserConstructionScript final
{
public:
	struct FVector                                CallFunc_Conv_IntToVector_ReturnValue;             // 0x0000(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_SelectFloat_ReturnValue;                  // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ASoundPath_C*                           K2Node_DynamicCast_AsSound_Path;                   // 0x0020(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_29[0x7];                                       // 0x0029(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_MakeVector_ReturnValue;                   // 0x0030(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             CallFunc_K2_SetRelativeLocation_SweepHitResult;    // 0x0048(0x0100)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	struct FVector                                CallFunc_GetForwardVector_ReturnValue;             // 0x0148(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FTransform                             CallFunc_K2_GetComponentToWorld_ReturnValue;       // 0x0160(0x0060)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Multiply_VectorVector_ReturnValue;        // 0x01C0(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakTransform_Location;                  // 0x01D8(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_BreakTransform_Rotation;                  // 0x01F0(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_BreakTransform_Scale;                     // 0x0208(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Add_VectorVector_ReturnValue;             // 0x0220(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AItemSlot_C*                            K2Node_DynamicCast_AsItem_Slot;                    // 0x0238(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0240(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BottleSlot_C_UserConstructionScript) == 0x000010, "Wrong alignment on BottleSlot_C_UserConstructionScript");
static_assert(sizeof(BottleSlot_C_UserConstructionScript) == 0x000250, "Wrong size on BottleSlot_C_UserConstructionScript");
static_assert(offsetof(BottleSlot_C_UserConstructionScript, CallFunc_Conv_IntToVector_ReturnValue) == 0x000000, "Member 'BottleSlot_C_UserConstructionScript::CallFunc_Conv_IntToVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(BottleSlot_C_UserConstructionScript, CallFunc_SelectFloat_ReturnValue) == 0x000018, "Member 'BottleSlot_C_UserConstructionScript::CallFunc_SelectFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(BottleSlot_C_UserConstructionScript, K2Node_DynamicCast_AsSound_Path) == 0x000020, "Member 'BottleSlot_C_UserConstructionScript::K2Node_DynamicCast_AsSound_Path' has a wrong offset!");
static_assert(offsetof(BottleSlot_C_UserConstructionScript, K2Node_DynamicCast_bSuccess) == 0x000028, "Member 'BottleSlot_C_UserConstructionScript::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BottleSlot_C_UserConstructionScript, CallFunc_MakeVector_ReturnValue) == 0x000030, "Member 'BottleSlot_C_UserConstructionScript::CallFunc_MakeVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(BottleSlot_C_UserConstructionScript, CallFunc_K2_SetRelativeLocation_SweepHitResult) == 0x000048, "Member 'BottleSlot_C_UserConstructionScript::CallFunc_K2_SetRelativeLocation_SweepHitResult' has a wrong offset!");
static_assert(offsetof(BottleSlot_C_UserConstructionScript, CallFunc_GetForwardVector_ReturnValue) == 0x000148, "Member 'BottleSlot_C_UserConstructionScript::CallFunc_GetForwardVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(BottleSlot_C_UserConstructionScript, CallFunc_K2_GetComponentToWorld_ReturnValue) == 0x000160, "Member 'BottleSlot_C_UserConstructionScript::CallFunc_K2_GetComponentToWorld_ReturnValue' has a wrong offset!");
static_assert(offsetof(BottleSlot_C_UserConstructionScript, CallFunc_Multiply_VectorVector_ReturnValue) == 0x0001C0, "Member 'BottleSlot_C_UserConstructionScript::CallFunc_Multiply_VectorVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(BottleSlot_C_UserConstructionScript, CallFunc_BreakTransform_Location) == 0x0001D8, "Member 'BottleSlot_C_UserConstructionScript::CallFunc_BreakTransform_Location' has a wrong offset!");
static_assert(offsetof(BottleSlot_C_UserConstructionScript, CallFunc_BreakTransform_Rotation) == 0x0001F0, "Member 'BottleSlot_C_UserConstructionScript::CallFunc_BreakTransform_Rotation' has a wrong offset!");
static_assert(offsetof(BottleSlot_C_UserConstructionScript, CallFunc_BreakTransform_Scale) == 0x000208, "Member 'BottleSlot_C_UserConstructionScript::CallFunc_BreakTransform_Scale' has a wrong offset!");
static_assert(offsetof(BottleSlot_C_UserConstructionScript, CallFunc_Add_VectorVector_ReturnValue) == 0x000220, "Member 'BottleSlot_C_UserConstructionScript::CallFunc_Add_VectorVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(BottleSlot_C_UserConstructionScript, K2Node_DynamicCast_AsItem_Slot) == 0x000238, "Member 'BottleSlot_C_UserConstructionScript::K2Node_DynamicCast_AsItem_Slot' has a wrong offset!");
static_assert(offsetof(BottleSlot_C_UserConstructionScript, K2Node_DynamicCast_bSuccess_1) == 0x000240, "Member 'BottleSlot_C_UserConstructionScript::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");

}

