#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Task_Machine

#include "Basic.hpp"

#include "Str_ItemSpawnRequest_structs.hpp"
#include "Str_ItemState_structs.hpp"
#include "Str_Item_structs.hpp"
#include "Str_ItemSpawnLocation_structs.hpp"


namespace SDK::Params
{

// Function Task_Machine.Task_Machine_C.Check Machines
// 0x0030 (0x0030 - 0x0000)
struct Task_Machine_C_Check_Machines final
{
public:
	bool                                          End;                                               // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         _Count;                                            // 0x0004(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Finished;                                          // 0x0008(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_9[0x3];                                        // 0x0009(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Array_Index_Variable;                     // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0014(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1C[0x4];                                       // 0x001C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AMachinePannel_C*                       CallFunc_Array_Get_Item;                           // 0x0020(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_IntInt_ReturnValue;               // 0x0029(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Task_Machine_C_Check_Machines) == 0x000008, "Wrong alignment on Task_Machine_C_Check_Machines");
static_assert(sizeof(Task_Machine_C_Check_Machines) == 0x000030, "Wrong size on Task_Machine_C_Check_Machines");
static_assert(offsetof(Task_Machine_C_Check_Machines, End) == 0x000000, "Member 'Task_Machine_C_Check_Machines::End' has a wrong offset!");
static_assert(offsetof(Task_Machine_C_Check_Machines, _Count) == 0x000004, "Member 'Task_Machine_C_Check_Machines::_Count' has a wrong offset!");
static_assert(offsetof(Task_Machine_C_Check_Machines, Finished) == 0x000008, "Member 'Task_Machine_C_Check_Machines::Finished' has a wrong offset!");
static_assert(offsetof(Task_Machine_C_Check_Machines, Temp_int_Array_Index_Variable) == 0x00000C, "Member 'Task_Machine_C_Check_Machines::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(Task_Machine_C_Check_Machines, Temp_int_Loop_Counter_Variable) == 0x000010, "Member 'Task_Machine_C_Check_Machines::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(Task_Machine_C_Check_Machines, CallFunc_Add_IntInt_ReturnValue) == 0x000014, "Member 'Task_Machine_C_Check_Machines::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(Task_Machine_C_Check_Machines, CallFunc_Array_Length_ReturnValue) == 0x000018, "Member 'Task_Machine_C_Check_Machines::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(Task_Machine_C_Check_Machines, CallFunc_Array_Get_Item) == 0x000020, "Member 'Task_Machine_C_Check_Machines::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(Task_Machine_C_Check_Machines, CallFunc_Less_IntInt_ReturnValue) == 0x000028, "Member 'Task_Machine_C_Check_Machines::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(Task_Machine_C_Check_Machines, CallFunc_Greater_IntInt_ReturnValue) == 0x000029, "Member 'Task_Machine_C_Check_Machines::CallFunc_Greater_IntInt_ReturnValue' has a wrong offset!");

// Function Task_Machine.Task_Machine_C.ExecuteUbergraph_Task_Machine
// 0x01B8 (0x01B8 - 0x0000)
struct Task_Machine_C_ExecuteUbergraph_Task_Machine final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FStr_ItemSpawnRequest                  K2Node_MakeStruct_Str_ItemSpawnRequest;            // 0x0004(0x0008)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_C[0x4];                                        // 0x000C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FStr_ItemSpawnRequest>          K2Node_MakeArray_Array;                            // 0x0010(0x0010)(ReferenceParm)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0024(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0028(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable_1;                   // 0x002C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable_1;                  // 0x0030(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_1;                 // 0x0034(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable_2;                  // 0x0038(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_2;                 // 0x003C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable_2;                   // 0x0040(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0044(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable_3;                   // 0x0048(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable_3;                  // 0x004C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AMachinePannel_C*                       CallFunc_Array_Get_Item;                           // 0x0050(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_3;                 // 0x0058(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable_4;                   // 0x005C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable_4;                  // 0x0060(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable_5;                  // 0x0064(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_4;                 // 0x0068(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x006C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_6D[0x3];                                       // 0x006D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue_5;                 // 0x0070(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable_5;                   // 0x0074(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        K2Node_Event_Delay;                                // 0x0078(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class ABottleSlot_C*>                  CallFunc_GetAllActorsOfClass_OutActors;            // 0x0080(0x0010)(ReferenceParm)
	int32                                         CallFunc_Array_Length_ReturnValue_1;               // 0x0090(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_94[0x4];                                       // 0x0094(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class AMachinePannel_C*>               CallFunc_GetAllActorsOfClass_OutActors_1;          // 0x0098(0x0010)(ReferenceParm)
	int32                                         Temp_int_Loop_Counter_Variable_6;                  // 0x00A8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_1;                // 0x00AC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_AD[0x3];                                       // 0x00AD(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue_6;                 // 0x00B0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x00B4(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Check_Machines_End;                       // 0x00C4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_C5[0x3];                                       // 0x00C5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class AMachinePannel_C*                       CallFunc_Array_Get_Item_1;                         // 0x00C8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_2;               // 0x00D0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_2;                // 0x00D4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_D5[0x3];                                       // 0x00D5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class AMachinePannel_C*                       CallFunc_Array_Get_Item_2;                         // 0x00D8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_3;               // 0x00E0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_3;                // 0x00E4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_E5[0x3];                                       // 0x00E5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class ABottleSlot_C*                          CallFunc_Array_Get_Item_3;                         // 0x00E8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_4;               // 0x00F0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_4;                // 0x00F4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_F5[0x3];                                       // 0x00F5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FStr_ItemState                         K2Node_MakeStruct_Str_ItemState;                   // 0x00F8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable_6;                   // 0x0100(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_104[0x4];                                      // 0x0104(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AMachinePannel_C*                       CallFunc_Array_Get_Item_4;                         // 0x0108(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ABottleSlot_C*                          CallFunc_Array_Get_Item_5;                         // 0x0110(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_5;               // 0x0118(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FStr_ItemState                         K2Node_MakeStruct_Str_ItemState_1;                 // 0x011C(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_5;                // 0x0124(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_125[0x3];                                      // 0x0125(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FStr_Item                              K2Node_MakeStruct_Str_Item;                        // 0x0128(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FStr_ItemState                         K2Node_MakeStruct_Str_ItemState_2;                 // 0x0138(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Conv_IntToString_ReturnValue;             // 0x0140(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Conv_IntToString_ReturnValue_1;           // 0x0150(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Concat_StrStr_ReturnValue;                // 0x0160(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_6;                // 0x0170(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_171[0x3];                                      // 0x0171(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Length_ReturnValue_6;               // 0x0174(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_7;                // 0x0178(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FStr_ItemSpawnLocation                 CallFunc_Spawn_Item_Location;                      // 0x0179(0x0002)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_17B[0x5];                                      // 0x017B(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class ABottleSlot_C*                          CallFunc_Array_Get_Item_6;                         // 0x0180(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_IntInt_ReturnValue;            // 0x0188(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_189[0x7];                                      // 0x0189(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_SelectString_ReturnValue;                 // 0x0190(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Concat_StrStr_ReturnValue_1;              // 0x01A0(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	float                                         CallFunc_Delay_Duration_ImplicitCast;              // 0x01B0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Task_Machine_C_ExecuteUbergraph_Task_Machine) == 0x000008, "Wrong alignment on Task_Machine_C_ExecuteUbergraph_Task_Machine");
static_assert(sizeof(Task_Machine_C_ExecuteUbergraph_Task_Machine) == 0x0001B8, "Wrong size on Task_Machine_C_ExecuteUbergraph_Task_Machine");
static_assert(offsetof(Task_Machine_C_ExecuteUbergraph_Task_Machine, EntryPoint) == 0x000000, "Member 'Task_Machine_C_ExecuteUbergraph_Task_Machine::EntryPoint' has a wrong offset!");
static_assert(offsetof(Task_Machine_C_ExecuteUbergraph_Task_Machine, K2Node_MakeStruct_Str_ItemSpawnRequest) == 0x000004, "Member 'Task_Machine_C_ExecuteUbergraph_Task_Machine::K2Node_MakeStruct_Str_ItemSpawnRequest' has a wrong offset!");
static_assert(offsetof(Task_Machine_C_ExecuteUbergraph_Task_Machine, K2Node_MakeArray_Array) == 0x000010, "Member 'Task_Machine_C_ExecuteUbergraph_Task_Machine::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(Task_Machine_C_ExecuteUbergraph_Task_Machine, Temp_int_Array_Index_Variable) == 0x000020, "Member 'Task_Machine_C_ExecuteUbergraph_Task_Machine::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(Task_Machine_C_ExecuteUbergraph_Task_Machine, Temp_int_Loop_Counter_Variable) == 0x000024, "Member 'Task_Machine_C_ExecuteUbergraph_Task_Machine::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(Task_Machine_C_ExecuteUbergraph_Task_Machine, CallFunc_Add_IntInt_ReturnValue) == 0x000028, "Member 'Task_Machine_C_ExecuteUbergraph_Task_Machine::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(Task_Machine_C_ExecuteUbergraph_Task_Machine, Temp_int_Array_Index_Variable_1) == 0x00002C, "Member 'Task_Machine_C_ExecuteUbergraph_Task_Machine::Temp_int_Array_Index_Variable_1' has a wrong offset!");
static_assert(offsetof(Task_Machine_C_ExecuteUbergraph_Task_Machine, Temp_int_Loop_Counter_Variable_1) == 0x000030, "Member 'Task_Machine_C_ExecuteUbergraph_Task_Machine::Temp_int_Loop_Counter_Variable_1' has a wrong offset!");
static_assert(offsetof(Task_Machine_C_ExecuteUbergraph_Task_Machine, CallFunc_Add_IntInt_ReturnValue_1) == 0x000034, "Member 'Task_Machine_C_ExecuteUbergraph_Task_Machine::CallFunc_Add_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Task_Machine_C_ExecuteUbergraph_Task_Machine, Temp_int_Loop_Counter_Variable_2) == 0x000038, "Member 'Task_Machine_C_ExecuteUbergraph_Task_Machine::Temp_int_Loop_Counter_Variable_2' has a wrong offset!");
static_assert(offsetof(Task_Machine_C_ExecuteUbergraph_Task_Machine, CallFunc_Add_IntInt_ReturnValue_2) == 0x00003C, "Member 'Task_Machine_C_ExecuteUbergraph_Task_Machine::CallFunc_Add_IntInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(Task_Machine_C_ExecuteUbergraph_Task_Machine, Temp_int_Array_Index_Variable_2) == 0x000040, "Member 'Task_Machine_C_ExecuteUbergraph_Task_Machine::Temp_int_Array_Index_Variable_2' has a wrong offset!");
static_assert(offsetof(Task_Machine_C_ExecuteUbergraph_Task_Machine, CallFunc_Array_Length_ReturnValue) == 0x000044, "Member 'Task_Machine_C_ExecuteUbergraph_Task_Machine::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(Task_Machine_C_ExecuteUbergraph_Task_Machine, Temp_int_Array_Index_Variable_3) == 0x000048, "Member 'Task_Machine_C_ExecuteUbergraph_Task_Machine::Temp_int_Array_Index_Variable_3' has a wrong offset!");
static_assert(offsetof(Task_Machine_C_ExecuteUbergraph_Task_Machine, Temp_int_Loop_Counter_Variable_3) == 0x00004C, "Member 'Task_Machine_C_ExecuteUbergraph_Task_Machine::Temp_int_Loop_Counter_Variable_3' has a wrong offset!");
static_assert(offsetof(Task_Machine_C_ExecuteUbergraph_Task_Machine, CallFunc_Array_Get_Item) == 0x000050, "Member 'Task_Machine_C_ExecuteUbergraph_Task_Machine::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(Task_Machine_C_ExecuteUbergraph_Task_Machine, CallFunc_Add_IntInt_ReturnValue_3) == 0x000058, "Member 'Task_Machine_C_ExecuteUbergraph_Task_Machine::CallFunc_Add_IntInt_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(Task_Machine_C_ExecuteUbergraph_Task_Machine, Temp_int_Array_Index_Variable_4) == 0x00005C, "Member 'Task_Machine_C_ExecuteUbergraph_Task_Machine::Temp_int_Array_Index_Variable_4' has a wrong offset!");
static_assert(offsetof(Task_Machine_C_ExecuteUbergraph_Task_Machine, Temp_int_Loop_Counter_Variable_4) == 0x000060, "Member 'Task_Machine_C_ExecuteUbergraph_Task_Machine::Temp_int_Loop_Counter_Variable_4' has a wrong offset!");
static_assert(offsetof(Task_Machine_C_ExecuteUbergraph_Task_Machine, Temp_int_Loop_Counter_Variable_5) == 0x000064, "Member 'Task_Machine_C_ExecuteUbergraph_Task_Machine::Temp_int_Loop_Counter_Variable_5' has a wrong offset!");
static_assert(offsetof(Task_Machine_C_ExecuteUbergraph_Task_Machine, CallFunc_Add_IntInt_ReturnValue_4) == 0x000068, "Member 'Task_Machine_C_ExecuteUbergraph_Task_Machine::CallFunc_Add_IntInt_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(Task_Machine_C_ExecuteUbergraph_Task_Machine, CallFunc_Less_IntInt_ReturnValue) == 0x00006C, "Member 'Task_Machine_C_ExecuteUbergraph_Task_Machine::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(Task_Machine_C_ExecuteUbergraph_Task_Machine, CallFunc_Add_IntInt_ReturnValue_5) == 0x000070, "Member 'Task_Machine_C_ExecuteUbergraph_Task_Machine::CallFunc_Add_IntInt_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(Task_Machine_C_ExecuteUbergraph_Task_Machine, Temp_int_Array_Index_Variable_5) == 0x000074, "Member 'Task_Machine_C_ExecuteUbergraph_Task_Machine::Temp_int_Array_Index_Variable_5' has a wrong offset!");
static_assert(offsetof(Task_Machine_C_ExecuteUbergraph_Task_Machine, K2Node_Event_Delay) == 0x000078, "Member 'Task_Machine_C_ExecuteUbergraph_Task_Machine::K2Node_Event_Delay' has a wrong offset!");
static_assert(offsetof(Task_Machine_C_ExecuteUbergraph_Task_Machine, CallFunc_GetAllActorsOfClass_OutActors) == 0x000080, "Member 'Task_Machine_C_ExecuteUbergraph_Task_Machine::CallFunc_GetAllActorsOfClass_OutActors' has a wrong offset!");
static_assert(offsetof(Task_Machine_C_ExecuteUbergraph_Task_Machine, CallFunc_Array_Length_ReturnValue_1) == 0x000090, "Member 'Task_Machine_C_ExecuteUbergraph_Task_Machine::CallFunc_Array_Length_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Task_Machine_C_ExecuteUbergraph_Task_Machine, CallFunc_GetAllActorsOfClass_OutActors_1) == 0x000098, "Member 'Task_Machine_C_ExecuteUbergraph_Task_Machine::CallFunc_GetAllActorsOfClass_OutActors_1' has a wrong offset!");
static_assert(offsetof(Task_Machine_C_ExecuteUbergraph_Task_Machine, Temp_int_Loop_Counter_Variable_6) == 0x0000A8, "Member 'Task_Machine_C_ExecuteUbergraph_Task_Machine::Temp_int_Loop_Counter_Variable_6' has a wrong offset!");
static_assert(offsetof(Task_Machine_C_ExecuteUbergraph_Task_Machine, CallFunc_Less_IntInt_ReturnValue_1) == 0x0000AC, "Member 'Task_Machine_C_ExecuteUbergraph_Task_Machine::CallFunc_Less_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Task_Machine_C_ExecuteUbergraph_Task_Machine, CallFunc_Add_IntInt_ReturnValue_6) == 0x0000B0, "Member 'Task_Machine_C_ExecuteUbergraph_Task_Machine::CallFunc_Add_IntInt_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(Task_Machine_C_ExecuteUbergraph_Task_Machine, K2Node_CreateDelegate_OutputDelegate) == 0x0000B4, "Member 'Task_Machine_C_ExecuteUbergraph_Task_Machine::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(Task_Machine_C_ExecuteUbergraph_Task_Machine, CallFunc_Check_Machines_End) == 0x0000C4, "Member 'Task_Machine_C_ExecuteUbergraph_Task_Machine::CallFunc_Check_Machines_End' has a wrong offset!");
static_assert(offsetof(Task_Machine_C_ExecuteUbergraph_Task_Machine, CallFunc_Array_Get_Item_1) == 0x0000C8, "Member 'Task_Machine_C_ExecuteUbergraph_Task_Machine::CallFunc_Array_Get_Item_1' has a wrong offset!");
static_assert(offsetof(Task_Machine_C_ExecuteUbergraph_Task_Machine, CallFunc_Array_Length_ReturnValue_2) == 0x0000D0, "Member 'Task_Machine_C_ExecuteUbergraph_Task_Machine::CallFunc_Array_Length_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(Task_Machine_C_ExecuteUbergraph_Task_Machine, CallFunc_Less_IntInt_ReturnValue_2) == 0x0000D4, "Member 'Task_Machine_C_ExecuteUbergraph_Task_Machine::CallFunc_Less_IntInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(Task_Machine_C_ExecuteUbergraph_Task_Machine, CallFunc_Array_Get_Item_2) == 0x0000D8, "Member 'Task_Machine_C_ExecuteUbergraph_Task_Machine::CallFunc_Array_Get_Item_2' has a wrong offset!");
static_assert(offsetof(Task_Machine_C_ExecuteUbergraph_Task_Machine, CallFunc_Array_Length_ReturnValue_3) == 0x0000E0, "Member 'Task_Machine_C_ExecuteUbergraph_Task_Machine::CallFunc_Array_Length_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(Task_Machine_C_ExecuteUbergraph_Task_Machine, CallFunc_Less_IntInt_ReturnValue_3) == 0x0000E4, "Member 'Task_Machine_C_ExecuteUbergraph_Task_Machine::CallFunc_Less_IntInt_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(Task_Machine_C_ExecuteUbergraph_Task_Machine, CallFunc_Array_Get_Item_3) == 0x0000E8, "Member 'Task_Machine_C_ExecuteUbergraph_Task_Machine::CallFunc_Array_Get_Item_3' has a wrong offset!");
static_assert(offsetof(Task_Machine_C_ExecuteUbergraph_Task_Machine, CallFunc_Array_Length_ReturnValue_4) == 0x0000F0, "Member 'Task_Machine_C_ExecuteUbergraph_Task_Machine::CallFunc_Array_Length_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(Task_Machine_C_ExecuteUbergraph_Task_Machine, CallFunc_Less_IntInt_ReturnValue_4) == 0x0000F4, "Member 'Task_Machine_C_ExecuteUbergraph_Task_Machine::CallFunc_Less_IntInt_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(Task_Machine_C_ExecuteUbergraph_Task_Machine, K2Node_MakeStruct_Str_ItemState) == 0x0000F8, "Member 'Task_Machine_C_ExecuteUbergraph_Task_Machine::K2Node_MakeStruct_Str_ItemState' has a wrong offset!");
static_assert(offsetof(Task_Machine_C_ExecuteUbergraph_Task_Machine, Temp_int_Array_Index_Variable_6) == 0x000100, "Member 'Task_Machine_C_ExecuteUbergraph_Task_Machine::Temp_int_Array_Index_Variable_6' has a wrong offset!");
static_assert(offsetof(Task_Machine_C_ExecuteUbergraph_Task_Machine, CallFunc_Array_Get_Item_4) == 0x000108, "Member 'Task_Machine_C_ExecuteUbergraph_Task_Machine::CallFunc_Array_Get_Item_4' has a wrong offset!");
static_assert(offsetof(Task_Machine_C_ExecuteUbergraph_Task_Machine, CallFunc_Array_Get_Item_5) == 0x000110, "Member 'Task_Machine_C_ExecuteUbergraph_Task_Machine::CallFunc_Array_Get_Item_5' has a wrong offset!");
static_assert(offsetof(Task_Machine_C_ExecuteUbergraph_Task_Machine, CallFunc_Array_Length_ReturnValue_5) == 0x000118, "Member 'Task_Machine_C_ExecuteUbergraph_Task_Machine::CallFunc_Array_Length_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(Task_Machine_C_ExecuteUbergraph_Task_Machine, K2Node_MakeStruct_Str_ItemState_1) == 0x00011C, "Member 'Task_Machine_C_ExecuteUbergraph_Task_Machine::K2Node_MakeStruct_Str_ItemState_1' has a wrong offset!");
static_assert(offsetof(Task_Machine_C_ExecuteUbergraph_Task_Machine, CallFunc_Less_IntInt_ReturnValue_5) == 0x000124, "Member 'Task_Machine_C_ExecuteUbergraph_Task_Machine::CallFunc_Less_IntInt_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(Task_Machine_C_ExecuteUbergraph_Task_Machine, K2Node_MakeStruct_Str_Item) == 0x000128, "Member 'Task_Machine_C_ExecuteUbergraph_Task_Machine::K2Node_MakeStruct_Str_Item' has a wrong offset!");
static_assert(offsetof(Task_Machine_C_ExecuteUbergraph_Task_Machine, K2Node_MakeStruct_Str_ItemState_2) == 0x000138, "Member 'Task_Machine_C_ExecuteUbergraph_Task_Machine::K2Node_MakeStruct_Str_ItemState_2' has a wrong offset!");
static_assert(offsetof(Task_Machine_C_ExecuteUbergraph_Task_Machine, CallFunc_Conv_IntToString_ReturnValue) == 0x000140, "Member 'Task_Machine_C_ExecuteUbergraph_Task_Machine::CallFunc_Conv_IntToString_ReturnValue' has a wrong offset!");
static_assert(offsetof(Task_Machine_C_ExecuteUbergraph_Task_Machine, CallFunc_Conv_IntToString_ReturnValue_1) == 0x000150, "Member 'Task_Machine_C_ExecuteUbergraph_Task_Machine::CallFunc_Conv_IntToString_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Task_Machine_C_ExecuteUbergraph_Task_Machine, CallFunc_Concat_StrStr_ReturnValue) == 0x000160, "Member 'Task_Machine_C_ExecuteUbergraph_Task_Machine::CallFunc_Concat_StrStr_ReturnValue' has a wrong offset!");
static_assert(offsetof(Task_Machine_C_ExecuteUbergraph_Task_Machine, CallFunc_Less_IntInt_ReturnValue_6) == 0x000170, "Member 'Task_Machine_C_ExecuteUbergraph_Task_Machine::CallFunc_Less_IntInt_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(Task_Machine_C_ExecuteUbergraph_Task_Machine, CallFunc_Array_Length_ReturnValue_6) == 0x000174, "Member 'Task_Machine_C_ExecuteUbergraph_Task_Machine::CallFunc_Array_Length_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(Task_Machine_C_ExecuteUbergraph_Task_Machine, CallFunc_Less_IntInt_ReturnValue_7) == 0x000178, "Member 'Task_Machine_C_ExecuteUbergraph_Task_Machine::CallFunc_Less_IntInt_ReturnValue_7' has a wrong offset!");
static_assert(offsetof(Task_Machine_C_ExecuteUbergraph_Task_Machine, CallFunc_Spawn_Item_Location) == 0x000179, "Member 'Task_Machine_C_ExecuteUbergraph_Task_Machine::CallFunc_Spawn_Item_Location' has a wrong offset!");
static_assert(offsetof(Task_Machine_C_ExecuteUbergraph_Task_Machine, CallFunc_Array_Get_Item_6) == 0x000180, "Member 'Task_Machine_C_ExecuteUbergraph_Task_Machine::CallFunc_Array_Get_Item_6' has a wrong offset!");
static_assert(offsetof(Task_Machine_C_ExecuteUbergraph_Task_Machine, CallFunc_EqualEqual_IntInt_ReturnValue) == 0x000188, "Member 'Task_Machine_C_ExecuteUbergraph_Task_Machine::CallFunc_EqualEqual_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(Task_Machine_C_ExecuteUbergraph_Task_Machine, CallFunc_SelectString_ReturnValue) == 0x000190, "Member 'Task_Machine_C_ExecuteUbergraph_Task_Machine::CallFunc_SelectString_ReturnValue' has a wrong offset!");
static_assert(offsetof(Task_Machine_C_ExecuteUbergraph_Task_Machine, CallFunc_Concat_StrStr_ReturnValue_1) == 0x0001A0, "Member 'Task_Machine_C_ExecuteUbergraph_Task_Machine::CallFunc_Concat_StrStr_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Task_Machine_C_ExecuteUbergraph_Task_Machine, CallFunc_Delay_Duration_ImplicitCast) == 0x0001B0, "Member 'Task_Machine_C_ExecuteUbergraph_Task_Machine::CallFunc_Delay_Duration_ImplicitCast' has a wrong offset!");

// Function Task_Machine.Task_Machine_C.Start Task
// 0x0008 (0x0008 - 0x0000)
struct Task_Machine_C_Start_Task final
{
public:
	double                                        Delay;                                             // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Task_Machine_C_Start_Task) == 0x000008, "Wrong alignment on Task_Machine_C_Start_Task");
static_assert(sizeof(Task_Machine_C_Start_Task) == 0x000008, "Wrong size on Task_Machine_C_Start_Task");
static_assert(offsetof(Task_Machine_C_Start_Task, Delay) == 0x000000, "Member 'Task_Machine_C_Start_Task::Delay' has a wrong offset!");

// Function Task_Machine.Task_Machine_C.Suffle Bottles
// 0x0048 (0x0048 - 0x0000)
struct Task_Machine_C_Suffle_Bottles final
{
public:
	int32                                         Temp_int_Variable;                                 // 0x0000(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable_1;                               // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable_2;                               // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable_3;                               // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable_4;                               // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable_5;                               // 0x0014(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable_6;                               // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable_7;                               // 0x001C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable_8;                               // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0024(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0028(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_Select_Default;                             // 0x002C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0030(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_34[0x4];                                       // 0x0034(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class ABottleSlot_C*                          CallFunc_Array_Get_Item;                           // 0x0038(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0040(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0044(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Task_Machine_C_Suffle_Bottles) == 0x000008, "Wrong alignment on Task_Machine_C_Suffle_Bottles");
static_assert(sizeof(Task_Machine_C_Suffle_Bottles) == 0x000048, "Wrong size on Task_Machine_C_Suffle_Bottles");
static_assert(offsetof(Task_Machine_C_Suffle_Bottles, Temp_int_Variable) == 0x000000, "Member 'Task_Machine_C_Suffle_Bottles::Temp_int_Variable' has a wrong offset!");
static_assert(offsetof(Task_Machine_C_Suffle_Bottles, Temp_int_Variable_1) == 0x000004, "Member 'Task_Machine_C_Suffle_Bottles::Temp_int_Variable_1' has a wrong offset!");
static_assert(offsetof(Task_Machine_C_Suffle_Bottles, Temp_int_Variable_2) == 0x000008, "Member 'Task_Machine_C_Suffle_Bottles::Temp_int_Variable_2' has a wrong offset!");
static_assert(offsetof(Task_Machine_C_Suffle_Bottles, Temp_int_Variable_3) == 0x00000C, "Member 'Task_Machine_C_Suffle_Bottles::Temp_int_Variable_3' has a wrong offset!");
static_assert(offsetof(Task_Machine_C_Suffle_Bottles, Temp_int_Variable_4) == 0x000010, "Member 'Task_Machine_C_Suffle_Bottles::Temp_int_Variable_4' has a wrong offset!");
static_assert(offsetof(Task_Machine_C_Suffle_Bottles, Temp_int_Variable_5) == 0x000014, "Member 'Task_Machine_C_Suffle_Bottles::Temp_int_Variable_5' has a wrong offset!");
static_assert(offsetof(Task_Machine_C_Suffle_Bottles, Temp_int_Variable_6) == 0x000018, "Member 'Task_Machine_C_Suffle_Bottles::Temp_int_Variable_6' has a wrong offset!");
static_assert(offsetof(Task_Machine_C_Suffle_Bottles, Temp_int_Variable_7) == 0x00001C, "Member 'Task_Machine_C_Suffle_Bottles::Temp_int_Variable_7' has a wrong offset!");
static_assert(offsetof(Task_Machine_C_Suffle_Bottles, Temp_int_Variable_8) == 0x000020, "Member 'Task_Machine_C_Suffle_Bottles::Temp_int_Variable_8' has a wrong offset!");
static_assert(offsetof(Task_Machine_C_Suffle_Bottles, Temp_int_Array_Index_Variable) == 0x000024, "Member 'Task_Machine_C_Suffle_Bottles::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(Task_Machine_C_Suffle_Bottles, Temp_int_Loop_Counter_Variable) == 0x000028, "Member 'Task_Machine_C_Suffle_Bottles::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(Task_Machine_C_Suffle_Bottles, K2Node_Select_Default) == 0x00002C, "Member 'Task_Machine_C_Suffle_Bottles::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(Task_Machine_C_Suffle_Bottles, CallFunc_Add_IntInt_ReturnValue) == 0x000030, "Member 'Task_Machine_C_Suffle_Bottles::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(Task_Machine_C_Suffle_Bottles, CallFunc_Array_Get_Item) == 0x000038, "Member 'Task_Machine_C_Suffle_Bottles::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(Task_Machine_C_Suffle_Bottles, CallFunc_Array_Length_ReturnValue) == 0x000040, "Member 'Task_Machine_C_Suffle_Bottles::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(Task_Machine_C_Suffle_Bottles, CallFunc_Less_IntInt_ReturnValue) == 0x000044, "Member 'Task_Machine_C_Suffle_Bottles::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");

}

