#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_Menu_Rules

#include "Basic.hpp"

#include "W_Menu_Rules_classes.hpp"
#include "W_Menu_Rules_parameters.hpp"


namespace SDK
{

// Function W_Menu_Rules.W_Menu_Rules_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UW_Menu_Rules_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Menu_Rules_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_Menu_Rules.W_Menu_Rules_C.ExecuteUbergraph_W_Menu_Rules
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_Menu_Rules_C::ExecuteUbergraph_W_Menu_Rules(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Menu_Rules_C", "ExecuteUbergraph_W_Menu_Rules");

	Params::W_Menu_Rules_C_ExecuteUbergraph_W_Menu_Rules Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

