#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_Settings_Checkbox

#include "Basic.hpp"

#include "W_Settings_Checkbox_classes.hpp"
#include "W_Settings_Checkbox_parameters.hpp"


namespace SDK
{

// Function W_Settings_Checkbox.W_Settings_Checkbox_C.BndEvt__W_Settings_Checkbox_Button_K2Node_ComponentBoundEvent_0_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UW_Settings_Checkbox_C::BndEvt__W_Settings_Checkbox_Button_K2Node_ComponentBoundEvent_0_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Settings_Checkbox_C", "BndEvt__W_Settings_Checkbox_Button_K2Node_ComponentBoundEvent_0_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_Settings_Checkbox.W_Settings_Checkbox_C.BndEvt__W_Settings_Checkbox_Button_K2Node_ComponentBoundEvent_1_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UW_Settings_Checkbox_C::BndEvt__W_Settings_Checkbox_Button_K2Node_ComponentBoundEvent_1_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Settings_Checkbox_C", "BndEvt__W_Settings_Checkbox_Button_K2Node_ComponentBoundEvent_1_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_Settings_Checkbox.W_Settings_Checkbox_C.BndEvt__W_Settings_Checkbox_Button_K2Node_ComponentBoundEvent_4_OnButtonPressedEvent__DelegateSignature
// (BlueprintEvent)

void UW_Settings_Checkbox_C::BndEvt__W_Settings_Checkbox_Button_K2Node_ComponentBoundEvent_4_OnButtonPressedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Settings_Checkbox_C", "BndEvt__W_Settings_Checkbox_Button_K2Node_ComponentBoundEvent_4_OnButtonPressedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_Settings_Checkbox.W_Settings_Checkbox_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UW_Settings_Checkbox_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Settings_Checkbox_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_Settings_Checkbox.W_Settings_Checkbox_C.ExecuteUbergraph_W_Settings_Checkbox
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_Settings_Checkbox_C::ExecuteUbergraph_W_Settings_Checkbox(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Settings_Checkbox_C", "ExecuteUbergraph_W_Settings_Checkbox");

	Params::W_Settings_Checkbox_C_ExecuteUbergraph_W_Settings_Checkbox Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_Settings_Checkbox.W_Settings_Checkbox_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_Settings_Checkbox_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Settings_Checkbox_C", "PreConstruct");

	Params::W_Settings_Checkbox_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_Settings_Checkbox.W_Settings_Checkbox_C.Set Value
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    TRUE_0                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_Settings_Checkbox_C::Set_Value(bool TRUE_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Settings_Checkbox_C", "Set Value");

	Params::W_Settings_Checkbox_C_Set_Value Parms{};

	Parms.TRUE_0 = TRUE_0;

	UObject::ProcessEvent(Func, &Parms);
}

}

